# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(291, 210)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.rb_sequence = QtWidgets.QRadioButton(parent=self.centralwidget)
        self.rb_sequence.setGeometry(QtCore.QRect(10, 10, 121, 20))
        self.rb_sequence.setChecked(True)
        self.rb_sequence.setObjectName("rb_sequence")
        self.rb_omp = QtWidgets.QRadioButton(parent=self.centralwidget)
        self.rb_omp.setGeometry(QtCore.QRect(10, 40, 89, 20))
        self.rb_omp.setObjectName("rb_omp")
        self.rb_ocl = QtWidgets.QRadioButton(parent=self.centralwidget)
        self.rb_ocl.setGeometry(QtCore.QRect(10, 70, 89, 20))
        self.rb_ocl.setObjectName("rb_ocl")
        self.pushButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(10, 130, 271, 31))
        self.pushButton.setObjectName("pushButton")
        self.lb_timeResult = QtWidgets.QLabel(parent=self.centralwidget)
        self.lb_timeResult.setGeometry(QtCore.QRect(160, 170, 121, 20))
        self.lb_timeResult.setText("")
        self.lb_timeResult.setObjectName("lb_timeResult")
        self.horizontalSlider = QtWidgets.QSlider(parent=self.centralwidget)
        self.horizontalSlider.setGeometry(QtCore.QRect(120, 100, 160, 22))
        self.horizontalSlider.setMinimum(4)
        self.horizontalSlider.setMaximum(20)
        self.horizontalSlider.setSingleStep(2)
        self.horizontalSlider.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 100, 81, 16))
        self.label_2.setObjectName("label_2")
        self.verticalLayoutWidget = QtWidgets.QWidget(parent=self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(140, 10, 141, 81))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.rb_dilatation = QtWidgets.QRadioButton(parent=self.verticalLayoutWidget)
        self.rb_dilatation.setChecked(True)
        self.rb_dilatation.setAutoExclusive(True)
        self.rb_dilatation.setObjectName("rb_dilatation")
        self.verticalLayout.addWidget(self.rb_dilatation)
        self.rb_erode = QtWidgets.QRadioButton(parent=self.verticalLayoutWidget)
        self.rb_erode.setAutoExclusive(True)
        self.rb_erode.setObjectName("rb_erode")
        self.verticalLayout.addWidget(self.rb_erode)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 291, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Курсовая осень 2023"))
        self.rb_sequence.setText(_translate("MainWindow", "Последовательно"))
        self.rb_omp.setText(_translate("MainWindow", "OpenMP"))
        self.rb_ocl.setText(_translate("MainWindow", "OpenCL"))
        self.pushButton.setText(_translate("MainWindow", "Выполнить"))
        self.label_2.setText(_translate("MainWindow", "Размер ядра"))
        self.rb_dilatation.setText(_translate("MainWindow", "Дилатация"))
        self.rb_erode.setText(_translate("MainWindow", "Эрозия"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
